name: Continuous Integration
on: [push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-version: ['8.1', '8.2']
        symfony-version: ['^6.1', '^7.0']
    steps:
      - uses: actions/checkout@master
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug2
      - name: Install symfony version from matrix
        env:
          SYMFONY_VERSION: ${{ matrix.symfony-version }}
        run: composer require symfony/symfony:$SYMFONY_VERSION --no-update
      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction
      - name: Unit tests
        run: vendor/bin/phpunit tests/
